
#these you can change
USE_EB=TRUE
DEBUG=FALSE 
OPT=HIGH
MPI=TRUE
DIM=2

#leave these alone
ebase = conductivityDriver
CHOMBO_HOME = ../../chombo_lib
LibNames = EBAMRElliptic EBAMRTools Workshop EBTools AMRElliptic  AMRTools BoxTools BaseTools


base_dir = .
src_dirs = 

INPUT = conductivity.inputs

include $(CHOMBO_HOME)/mk/Make.example
