USE_EB = TRUE

ebase = navierDriver

CHOMBO_HOME = $(CHOMBO_TRUNK_LIB)

LibNames = EBAMRTimeDependent EBAMRElliptic EBAMRTools Workshop EBTools AMRElliptic AMRTimeDependent AMRTools BoxTools
base_dir = .
src_dirs = ../src

INPUT = ramp.2d.inputs

include $(CHOMBO_HOME)/mk/Make.example

